apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: insurehub-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - postgres-credentials.enc.yaml
  - rabbitmq-credentials.enc.yaml
  - backup-storage.enc.yaml
  - grafana-cloud-otlp.enc.yaml
  - lendhub-secrets.enc.yaml
  - insureassist-secrets.enc.yaml
  - insurehub-ussd-secrets.enc.yaml
